### PR TITLE
Daother 8060

### PR DESCRIPTION
**Pull request by j-s-135**
## Summary of Changes:
https://rcsbpdb.atlassian.net/browse/DAOTHER-8060

- [ ] Moved content type and file extension configuration settings to a separate built-in class called `Definitions.py`
- [ ] Created separate `client.yml` configuration file with trimmed-down set of settings needed for client-end usage
- [ ] Moved `ClientUtils.py` to separate directory branch, `rcsb/app/client` (and `rcsb/app/test-client`)
- [ ] ....
- [ ] ....

## Screenshot of Changes (or test)
(where applicable)

### Checklist:

- [ ] I followed the code style guidelines
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have tested the code / Added unit test(s)

### CODE REVIEW

**Comment by piehld** [comment]
Hi James, thanks for all the commits. Reviewing the code, I had a couple questions:
- For the `ClientUtils` and `testClientUtils`, why did you find it necessary to set the `configFilePath` to the `config.yml` instead of the more trimmed-down `client.yml` config file? I'm not sure I understand why the other parameters are necessary from the client-end perspective. If it was in order to get the "REPOSITORY_DIR_PATH" in testClientUtils, I think that should just be set explicitly as opposed to extracted from the configuration file.
- The `client.py` file—is that just for the front-end testing? If so, that's OK, but maybe put those files in a separate sub-directory, perhaps `rcsb/app/client/fe` (for 'front-end')
- Are all the packages imported by `requirements.txt` actually used? If not, are you able to remove (or comment out) any packages that aren't needed anymore? 

Also, there are a few other more stylistic things that we try to keep consistent with all of our packages. If possible, can you please try to standardize them?:
- Use `logger.info` or `logger.error` statements instead of `print` statements (e.g., in `testClientUtils`)
- All methods should be named with camelCasing (i.e., in `testClientUtils`, `test_simple_upload` should be `testSimpleUpload`)
- All quotes should be double-quotes (unless it's a quote inside a quote, which would necessitate the single quote)

**Comment by j-s-135** [comment]
Dennis, I don't have the 'client.yml' file on branch DAOTHER-8060, or any branch. Those files threw an error. That's the reason that I changed it to 'config.yml'. Regarding the client.py file, yes, it's front end, but ... I wouldn't say that the ClientUtils file is back end, so what's wrong with having all of them in the same folder? In fact, I have gui.py and client.py using the ClientUtils file. Regarding the other suggestions, I will do a pip freeze and try to fix the stylistic details.

**Comment by piehld** [comment]
@j-s-135 Whoops, I guess I forgot to add that file. Sorry about that. I've just added it now, so please pull the latest and check it out. I think we should point the ClientUtils and testClientUtils to using that file instead (`rcsb/app/config/client.yml`). 

For the directory organization, it doesn't really matter in terms of functionality, but for all of our other py-rcsb_* repos, we try to keep the directory trees as clean as possible to contain only the files necessary for the package. So, I think it's better to keep them separate from the core-package functionalities.

**Comment by j-s-135** [comment]
Client.py does not work with the repository at this time. We would have to rewrite the tests, and it's not clear whether it's possible. The issue is - where to put the test data? The unit tests post data to the endpoints themselves, and those are just configured to write data to the repository archive or deposit folders, so it's hard to reconfigure them to write data to the test folders. It's able to read from the test folders, so we create sample data files there dynamically. However, for download tests, we also need to dynamically create the deposit or archive files that it will read, so we need the full config.yml file that includes the paths. Also, for tear down, we would like to remove the files that have been created. So, the tests need most of the information in config.yml. The next problem is - how to prevent the tests from removing production files during tear down? I have made a new repository type for tests - rather than 'archive' or 'deposit' folders, it writes to a 'unit-test' folder, and also allows the names 'test', 'tests', 'unit-tests'. They're in the new Definitions file. If those are used, tests are safe even if used on the production server. We just need to provide very clear instructions to test writers.

**Comment by piehld** [comment]
Hmm, I see your points. I think adding those other methods to `Definitions.py` is a good idea; however, I don't think we should add 'test' etc. to those definitions. I think the tests themselves can just use the 'archive' or 'deposit' folders, and declare that explicitly in the `testClientUtils.py` file, just as was being done as if it was reading `config.yml`.

The end goal we want to achieve here is a `testClientUtils.py` file that contains test which simulate the same usage that a user of the repo would do in a real environment—i.e., having to explicitly state what repositoryType, depId, milestone etc. that they want to use for uploading their file. If you'd like me to try taking a stab at this, let me know.

**Comment by j-s-135** [comment]
I agree - "tests which simulate the same usage that a user of the repo would do in a real environment—i.e., having to explicitly state what repositoryType", but that's exactly what's happening. The repositoryType parameter has a value of 'unit-test', which is in the Definitions file so it passes validation, so a folder named 'unit-test' is formed and the files are saved there. For tear down, the entire unit-test folder is simply removed. We wouldn't want to remove the archive folder on tear down, so a test folder seems like a good alternative.

**Comment by piehld** [comment]
Thanks @j-s-135. I see the complication and your reasoning. Since you've gotten everything passing now, I'll go ahead and merge this.

Eventually I think we'll want to use real respositoryType parameters for the unit tests and remove the "test" values from the Definitions.py file, but that's a lower priority for now.

**Pull request merged**
